make:
	g++ main.cpp -o analyzer

hello-outfile:
	./analyzer ../Samples/hello.aja > hello.out

fib-outfile:
	./analyzer ../Samples/fib.aja > fib.out

shell-outfile:
	./analyzer ../Samples/shell.aja > shell.out

hello:
	./analyzer ../Samples/hello.aja

fib:
	./analyzer ../Samples/fib.aja

shell:
	./analyzer ../Samples/shell.aja

clean:
	rm -rf *.o *.out